# Site settings
title: Algoritmos y Programación II
description: >
  Página de la materia Algoritmos y Programación II, curso Buchwald.
  Facultad de Ingeniería, Universidad de Buenos Aires.

baseurl: "/tda_bg"

theme: minima
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

kramdown:
  input: GFM
  footnote_backlink: "&#x21A9;&#xFE0E;"
  highlighter: rouge

collections:
  tps:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: ""
      type: "tps"
    values:
      layout: tp
